version: '3'

services:
  app:
    build:
      context: .
    container_name: user_service_app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_NAME=user_db
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12
    container_name: user_service_postgresql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=user_db
    ports:
      - "5432:5432"