apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
            value: root
            - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgresql:{{ .Values.postgresPort }}/{{ .Values.dbName }}?useSSL=false"
            - name: SPRING_DATASOURCE_USERNAME
            value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: create-drop
---