name: Semantic Release

on:
  push:
    branches:
      - main
      - develop
jobs:    
  semantic_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17
        branches: | 
          [+]/[0-9]+.x
          [+]/[0-9]+.[0-9]+.x
          +/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
